[project]
name = "samuel"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "msal>=1.35.1",
    "notebook>=7.5.0",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "pandas-stubs~=2.3.3",
    "python-dotenv>=1.2.2",
    "streamlit>=1.45.1",
    "tqdm>=4.67.1",
    "watchdog>=6.0.0",
    "xlsxwriter>=3.2.9",
]
